package com.fingersome.dungeonmastery.lib;

public class PlayerInfo extends CharacterInfo
{

	public static final int GAME_DM_MAX = 1;
	public static boolean PLAYER_IS_DM;
	public static boolean PLAYER_IS_CHARACTER;
	
	public static String STAT_CHARACTER_FIRST_NAME;
	public static String STAT_CHARACTER_SECOND_NAME;
	public static String STAT_CHARACTER_BIO;
	public static int STAT_TRAIT_LEVEL;
	public static int STAT_MODIFIER_LEVEL = STAT_TRAIT_LEVEL /2;
	public static int STAT_TRAIT_EXP;
	public static String STAT_TRAIT_RACE;
	public static String STAT_TRAIT_CREATURETYPE;
	public static String STAT_TRAIT_CLASS;
	
	

	public static final int STAT_ABILITY_POINTS_TOTAL = 73;
	public static int STAT_ABILITY_POINTS_DEFAULT = 13;

	public static int STAT_POINTS_SPENT_STRENGTH 		= STAT_SKILL_DEFAULT;
	public static int STAT_POINTS_SPENT_DEXTERITY		= STAT_SKILL_DEFAULT;
	public static int STAT_POINTS_SPENT_CONSTITUTION	= STAT_SKILL_DEFAULT;
	public static int STAT_POINTS_SPENT_INTELLECT		= STAT_SKILL_DEFAULT;
	public static int STAT_POINTS_SPENT_WISDOM			= STAT_SKILL_DEFAULT;
	public static int STAT_POINTS_SPENT_CHARISMA		= STAT_SKILL_DEFAULT;
	
	public static int STAT_MODIFIER_STRENGTH 		= STAT_POINTS_SPENT_STRENGTH		/2;
	public static int STAT_MODIFIER_DEXTERITY		= STAT_POINTS_SPENT_DEXTERITY 		/2;
	public static int STAT_MODIFIER_CONSTITUTION	= STAT_POINTS_SPENT_CONSTITUTION 	/2;
	public static int STAT_MODIFIER_INTELLECT		= STAT_POINTS_SPENT_INTELLECT 		/2;
	public static int STAT_MODIFIER_WISDOM			= STAT_POINTS_SPENT_WISDOM 			/2;
	public static int STAT_MODIFIER_CHARISMA		= STAT_POINTS_SPENT_CHARISMA 		/2;
	
	public static int STAT_ABILITY_STRENGTH 		= STAT_ABILITY_DEFAULT + STAT_POINTS_SPENT_STRENGTH;
	public static int STAT_ABILITY_DEXTERITY 		= STAT_ABILITY_DEFAULT + STAT_POINTS_SPENT_DEXTERITY;
	public static int STAT_ABILITY_CONSTITUTION 	= STAT_ABILITY_DEFAULT + STAT_POINTS_SPENT_CONSTITUTION;
	public static int STAT_ABILITY_INTELLECT 		= STAT_ABILITY_DEFAULT;
	public static int STAT_ABILITY_WISDOM 			= STAT_ABILITY_DEFAULT;
	public static int STAT_ABILITY_CHARISMA 		= STAT_ABILITY_DEFAULT;
	
	public static int STAT_ABILITY_POINTS = 73 - (STAT_ABILITY_STRENGTH + STAT_ABILITY_DEXTERITY + 
													STAT_ABILITY_CONSTITUTION +	STAT_ABILITY_INTELLECT + 
													STAT_ABILITY_WISDOM + STAT_ABILITY_CHARISMA) ;
	
	
	
	public static int STAT_SKILL_POINTS_TOTAL;
	public static int STAT_SKILL_POINTS_SPENT;
	public static int STAT_SKILL_POINTS;
	
	public static boolean STAT_SKILL_TRAINED_DEFAULT;
	
	public static int STAT_SKILL_ACROBATICS 	= STAT_SKILL_DEFAULT;
	public static int STAT_SKILL_AGILITY 		= STAT_SKILL_DEFAULT;
	public static int STAT_SKILL_ARCANA 		= STAT_SKILL_DEFAULT;
	public static int STAT_SKILL_ATHLETICS		= STAT_SKILL_DEFAULT;
	public static int STAT_SKILL_BLUFF 			= STAT_SKILL_DEFAULT;
	public static int STAT_SKILL_DIPLOMACY 		= STAT_SKILL_DEFAULT;
	public static int STAT_SKILL_DUNGEONEERING 	= STAT_SKILL_DEFAULT;
	public static int STAT_SKILL_ENDURANCE 		= STAT_SKILL_DEFAULT;
	public static int STAT_SKILL_HEAL 			= STAT_SKILL_DEFAULT;
	public static int STAT_SKILL_HISTORY 		= STAT_SKILL_DEFAULT;
	public static int STAT_SKILL_INSIGHT 		= STAT_SKILL_DEFAULT;
	public static int STAT_SKILL_INTIMIDATE 	= STAT_SKILL_DEFAULT;
	public static int STAT_SKILL_NATURE 		= STAT_SKILL_DEFAULT;
	public static int STAT_SKILL_PERCEPTION 	= STAT_SKILL_DEFAULT;
	public static int STAT_SKILL_STEALTH 		= STAT_SKILL_DEFAULT;
	public static int STAT_SKILL_STREETWISE 	= STAT_SKILL_DEFAULT;
	public static int STAT_SKILL_RELIGION 		= STAT_SKILL_DEFAULT;
	public static int STAT_SKILL_THIEVERY 		= STAT_SKILL_DEFAULT;
	
	
	public static int STAT_TRAIT_CLASS_BASE_HEALTH;
	public static int STAT_DEFENSE_HEALTH_BASE 		= STAT_TRAIT_CLASS_BASE_HEALTH + STAT_MODIFIER_CONSTITUTION + STAT_MODIFIER_LEVEL;
	public static int STAT_DEFENSE_HEALTH_BLOODIED 	= STAT_DEFENSE_HEALTH_BASE /2;
	public static int STAT_DEFENSE_HEALTH;
	
	public static int STAT_DEFENSE_ARMOR 		= STAT_DEFENSES_DEFAULT + STAT_MODIFIER_CONSTITUTION 	
													+ STAT_MODIFIER_LEVEL;
	public static int STAT_DEFENSE_REFLEXES		= STAT_DEFENSES_DEFAULT + STAT_MODIFIER_DEXTERITY 		
													+ STAT_MODIFIER_LEVEL;
	public static int STAT_DEFENSE_FORTITUDE	= STAT_DEFENSES_DEFAULT + STAT_MODIFIER_CONSTITUTION 	
													+ STAT_MODIFIER_LEVEL;
	public static int STAT_DEFENSE_WILLPOWER	= STAT_DEFENSES_DEFAULT + STAT_MODIFIER_INTELLECT 		
													+ STAT_MODIFIER_LEVEL;

	public static int STAT_DEFENSE_RESIST_AIR;
	public static int STAT_DEFENSE_RESIST_EARTH;
	public static int STAT_DEFENSE_RESIST_FIRE;
	public static int STAT_DEFENSE_RESIST_WATER;
	public static int STAT_DEFENSE_RESIST_RADIENT;
	public static int STAT_DEFENSE_RESIST_NECROTIC;
	public static int STAT_DEFENSE_RESIST_ARCANE;
	public static int STAT_DEFENSE_RESIST_NATURE;
	public static int STAT_DEFENSE_RESIST_PSYCHIC;
	public static int STAT_DEFENSE_RESIST_PHYSICAL;
	
	
	
	public static int STAT_TRAIT_ALIGNMENT_MORAL_NUMERIC = 0;
	public static int STAT_TRAIT_ALIGNMENT_LEGAL_NUMERIC = 0;
	public static String STAT_TRAIT_ALIGNMENT_MORAL = "Neutral";	
	public static String STAT_TRAIT_ALIGNMENT_LEGAL = "Neutral";
	public static String STAT_TRAIT_ALIGNMENT = STAT_TRAIT_ALIGNMENT_LEGAL + " " + STAT_TRAIT_ALIGNMENT_MORAL;
}
