package com.fingersome.dungeonmasterycore.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelAltarCorellon extends ModelBase
{
    ModelRenderer Base;
    ModelRenderer Foot1;
    ModelRenderer Foot2;
    ModelRenderer Foot3;
    ModelRenderer Foot4;
    ModelRenderer Pillar1;
    ModelRenderer Pillar2;
    ModelRenderer Crossbar;
    ModelRenderer Platform;
    ModelRenderer Support1;
    ModelRenderer Support2;
    ModelRenderer Support3;
    ModelRenderer Support4;
    ModelRenderer Surface;
    ModelRenderer Spacer1;
    ModelRenderer Spacer2;
    ModelRenderer Top;
    ModelRenderer Ornament1;
    ModelRenderer Ornament2;
    ModelRenderer Ornament3;
    ModelRenderer Ornament4;
    ModelRenderer Cloth1;
    ModelRenderer Cloth2;
    ModelRenderer Symbol1;
    ModelRenderer Symbol2;
    ModelRenderer SymbolTopLeft1;
    ModelRenderer SymbolTopLeft2;
    ModelRenderer SymbolTopLeft3;
    ModelRenderer SymbolTopRight1;
    ModelRenderer SymbolTopRight2;
    ModelRenderer SymbolTopRight3;
    ModelRenderer SymbolBottomRight1;
    ModelRenderer SymbolBottomRight2;
    ModelRenderer SymbolBottomRight3;
    ModelRenderer SymbolBottomLeft1;
    ModelRenderer SymbolBottomLeft2;
    ModelRenderer SymbolBottomLeft3;
  
  public ModelAltarCorellon()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(0F, 0F, 0F, 10, 1, 6);
      Base.setRotationPoint(-5F, 22F, -3F);
      Base.setTextureSize(128, 64);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Foot1 = new ModelRenderer(this, 0, 0);
      Foot1.addBox(0F, 0F, 0F, 2, 1, 1);
      Foot1.setRotationPoint(-6F, 23F, 2F);
      Foot1.setTextureSize(128, 64);
      Foot1.mirror = true;
      setRotation(Foot1, 0F, 0F, 0F);
      Foot2 = new ModelRenderer(this, 0, 0);
      Foot2.addBox(0F, 0F, 0F, 2, 1, 1);
      Foot2.setRotationPoint(4F, 23F, 2F);
      Foot2.setTextureSize(128, 64);
      Foot2.mirror = true;
      setRotation(Foot2, 0F, 0F, 0F);
      Foot3 = new ModelRenderer(this, 0, 0);
      Foot3.addBox(0F, 0F, 0F, 2, 1, 1);
      Foot3.setRotationPoint(-6F, 23F, -3F);
      Foot3.setTextureSize(128, 64);
      Foot3.mirror = true;
      setRotation(Foot3, 0F, 0F, 0F);
      Foot4 = new ModelRenderer(this, 0, 0);
      Foot4.addBox(0F, 0F, 0F, 2, 1, 1);
      Foot4.setRotationPoint(4F, 23F, -3F);
      Foot4.setTextureSize(128, 64);
      Foot4.mirror = true;
      setRotation(Foot4, 0F, 0F, 0F);
      Pillar1 = new ModelRenderer(this, 0, 0);
      Pillar1.addBox(0F, 0F, 0F, 2, 6, 2);
      Pillar1.setRotationPoint(-4F, 16F, -1F);
      Pillar1.setTextureSize(128, 64);
      Pillar1.mirror = true;
      setRotation(Pillar1, 0F, 0F, 0F);
      Pillar2 = new ModelRenderer(this, 0, 0);
      Pillar2.addBox(0F, 0F, 0F, 2, 6, 2);
      Pillar2.setRotationPoint(2F, 16F, -1F);
      Pillar2.setTextureSize(128, 64);
      Pillar2.mirror = true;
      setRotation(Pillar2, 0F, 0F, 0F);
      Crossbar = new ModelRenderer(this, 0, 0);
      Crossbar.addBox(0F, 0F, 0F, 4, 1, 1);
      Crossbar.setRotationPoint(-2F, 19F, 0F);
      Crossbar.setTextureSize(128, 64);
      Crossbar.mirror = true;
      setRotation(Crossbar, 0F, 0F, 0F);
      Platform = new ModelRenderer(this, 0, 0);
      Platform.addBox(0F, 0F, 0F, 10, 1, 6);
      Platform.setRotationPoint(-5F, 15F, -3F);
      Platform.setTextureSize(128, 64);
      Platform.mirror = true;
      setRotation(Platform, 0F, 0F, 0F);
      Support1 = new ModelRenderer(this, 0, 0);
      Support1.addBox(0F, 0F, 0F, 1, 1, 1);
      Support1.setRotationPoint(-4F, 14F, 1F);
      Support1.setTextureSize(128, 64);
      Support1.mirror = true;
      setRotation(Support1, 0F, 0F, 0F);
      Support2 = new ModelRenderer(this, 0, 0);
      Support2.addBox(0F, 0F, 0F, 1, 1, 1);
      Support2.setRotationPoint(3F, 14F, 1F);
      Support2.setTextureSize(128, 64);
      Support2.mirror = true;
      setRotation(Support2, 0F, 0F, 0F);
      Support3 = new ModelRenderer(this, 0, 0);
      Support3.addBox(0F, 0F, 0F, 1, 1, 1);
      Support3.setRotationPoint(-4F, 14F, -2F);
      Support3.setTextureSize(128, 64);
      Support3.mirror = true;
      setRotation(Support3, 0F, 0F, 0F);
      Support4 = new ModelRenderer(this, 0, 0);
      Support4.addBox(0F, 0F, 0F, 1, 1, 1);
      Support4.setRotationPoint(3F, 14F, -2F);
      Support4.setTextureSize(128, 64);
      Support4.mirror = true;
      setRotation(Support4, 0F, 0F, 0F);
      Surface = new ModelRenderer(this, 0, 0);
      Surface.addBox(0F, 0F, 0F, 12, 1, 8);
      Surface.setRotationPoint(-6F, 13F, -4F);
      Surface.setTextureSize(128, 64);
      Surface.mirror = true;
      setRotation(Surface, 0F, 0F, 0F);
      Spacer1 = new ModelRenderer(this, 0, 0);
      Spacer1.addBox(0F, 0F, 0F, 1, 1, 4);
      Spacer1.setRotationPoint(-2F, 12F, -2F);
      Spacer1.setTextureSize(128, 64);
      Spacer1.mirror = true;
      setRotation(Spacer1, 0F, 0F, 0F);
      Spacer2 = new ModelRenderer(this, 15, 4);
      Spacer2.addBox(0F, 0F, 0F, 1, 1, 4);
      Spacer2.setRotationPoint(1F, 12F, -2F);
      Spacer2.setTextureSize(128, 64);
      Spacer2.mirror = true;
      setRotation(Spacer2, 0F, 0F, 0F);
      Top = new ModelRenderer(this, 0, 0);
      Top.addBox(0F, 0F, 0F, 6, 1, 6);
      Top.setRotationPoint(-3F, 11F, -3F);
      Top.setTextureSize(128, 64);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
      Ornament1 = new ModelRenderer(this, 0, 0);
      Ornament1.addBox(0F, 0F, 0F, 1, 1, 1);
      Ornament1.setRotationPoint(-5F, 12F, 2F);
      Ornament1.setTextureSize(128, 64);
      Ornament1.mirror = true;
      setRotation(Ornament1, 0F, 0F, 0F);
      Ornament2 = new ModelRenderer(this, 0, 0);
      Ornament2.addBox(0F, 0F, 0F, 1, 1, 1);
      Ornament2.setRotationPoint(4F, 12F, 2F);
      Ornament2.setTextureSize(128, 64);
      Ornament2.mirror = true;
      setRotation(Ornament2, 0F, 0F, 0F);
      Ornament3 = new ModelRenderer(this, 0, 0);
      Ornament3.addBox(0F, 0F, 0F, 1, 1, 1);
      Ornament3.setRotationPoint(-5F, 12F, -3F);
      Ornament3.setTextureSize(128, 64);
      Ornament3.mirror = true;
      setRotation(Ornament3, 0F, 0F, 0F);
      Ornament4 = new ModelRenderer(this, 0, 0);
      Ornament4.addBox(0F, 0F, 0F, 1, 1, 1);
      Ornament4.setRotationPoint(4F, 12F, -3F);
      Ornament4.setTextureSize(128, 64);
      Ornament4.mirror = true;
      setRotation(Ornament4, 0F, 0F, 0F);
      Cloth1 = new ModelRenderer(this, 0, 12);
      Cloth1.addBox(0F, 0F, 0F, 1, 6, 6);
      Cloth1.setRotationPoint(-6F, 14F, -3F);
      Cloth1.setTextureSize(128, 64);
      Cloth1.mirror = true;
      setRotation(Cloth1, 0F, 0F, 0F);
      Cloth2 = new ModelRenderer(this, 0, 12);
      Cloth2.addBox(0F, 0F, 0F, 1, 6, 6);
      Cloth2.setRotationPoint(5F, 14F, -3F);
      Cloth2.setTextureSize(128, 64);
      Cloth2.mirror = true;
      setRotation(Cloth2, 0F, 0F, 0F);
      Symbol1 = new ModelRenderer(this, 64, 0);
      Symbol1.addBox(0F, 0F, 0F, 2, 12, 2);
      Symbol1.setRotationPoint(-1F, -1F, -1F);
      Symbol1.setTextureSize(128, 64);
      Symbol1.mirror = true;
      setRotation(Symbol1, 0F, 0F, 0F);
      Symbol2 = new ModelRenderer(this, 64, 0);
      Symbol2.addBox(0F, 0F, 0F, 2, 10, 2);
      Symbol2.setRotationPoint(5F, 4F, -1F);
      Symbol2.setTextureSize(128, 64);
      Symbol2.mirror = true;
      setRotation(Symbol2, 0F, 0F, 1.570796F);
      SymbolTopLeft1 = new ModelRenderer(this, 64, 0);
      SymbolTopLeft1.addBox(0F, 0F, 0F, 1, 1, 2);
      SymbolTopLeft1.setRotationPoint(-2F, 3F, -1F);
      SymbolTopLeft1.setTextureSize(128, 64);
      SymbolTopLeft1.mirror = true;
      setRotation(SymbolTopLeft1, 0F, 0F, 0F);
      SymbolTopLeft2 = new ModelRenderer(this, 64, 0);
      SymbolTopLeft2.addBox(0F, 0F, 0F, 1, 1, 2);
      SymbolTopLeft2.setRotationPoint(-3F, 2F, -1F);
      SymbolTopLeft2.setTextureSize(128, 64);
      SymbolTopLeft2.mirror = true;
      setRotation(SymbolTopLeft2, 0F, 0F, 0F);
      SymbolTopLeft3 = new ModelRenderer(this, 64, 0);
      SymbolTopLeft3.addBox(0F, 0F, 0F, 1, 1, 2);
      SymbolTopLeft3.setRotationPoint(-4F, 1F, -1F);
      SymbolTopLeft3.setTextureSize(128, 64);
      SymbolTopLeft3.mirror = true;
      setRotation(SymbolTopLeft3, 0F, 0F, 0F);
      SymbolTopRight1 = new ModelRenderer(this, 64, 0);
      SymbolTopRight1.addBox(0F, 0F, 0F, 1, 1, 2);
      SymbolTopRight1.setRotationPoint(1F, 3F, -1F);
      SymbolTopRight1.setTextureSize(128, 64);
      SymbolTopRight1.mirror = true;
      setRotation(SymbolTopRight1, 0F, 0F, 0F);
      SymbolTopRight2 = new ModelRenderer(this, 64, 0);
      SymbolTopRight2.addBox(0F, 0F, 0F, 1, 1, 2);
      SymbolTopRight2.setRotationPoint(2F, 2F, -1F);
      SymbolTopRight2.setTextureSize(128, 64);
      SymbolTopRight2.mirror = true;
      setRotation(SymbolTopRight2, 0F, 0F, 0F);
      SymbolTopRight3 = new ModelRenderer(this, 64, 0);
      SymbolTopRight3.addBox(0F, 0F, 0F, 1, 1, 2);
      SymbolTopRight3.setRotationPoint(3F, 1F, -1F);
      SymbolTopRight3.setTextureSize(128, 64);
      SymbolTopRight3.mirror = true;
      setRotation(SymbolTopRight3, 0F, 0F, 0F);
      SymbolBottomRight1 = new ModelRenderer(this, 64, 0);
      SymbolBottomRight1.addBox(0F, 0F, 0F, 1, 1, 2);
      SymbolBottomRight1.setRotationPoint(1F, 6F, -1F);
      SymbolBottomRight1.setTextureSize(128, 64);
      SymbolBottomRight1.mirror = true;
      setRotation(SymbolBottomRight1, 0F, 0F, 0F);
      SymbolBottomRight2 = new ModelRenderer(this, 64, 0);
      SymbolBottomRight2.addBox(0F, 0F, 0F, 1, 1, 2);
      SymbolBottomRight2.setRotationPoint(2F, 7F, -1F);
      SymbolBottomRight2.setTextureSize(128, 64);
      SymbolBottomRight2.mirror = true;
      setRotation(SymbolBottomRight2, 0F, 0F, 0F);
      SymbolBottomRight3 = new ModelRenderer(this, 64, 0);
      SymbolBottomRight3.addBox(0F, 0F, 0F, 1, 1, 2);
      SymbolBottomRight3.setRotationPoint(3F, 8F, -1F);
      SymbolBottomRight3.setTextureSize(128, 64);
      SymbolBottomRight3.mirror = true;
      setRotation(SymbolBottomRight3, 0F, 0F, 0F);
      SymbolBottomLeft1 = new ModelRenderer(this, 64, 0);
      SymbolBottomLeft1.addBox(0F, 0F, 0F, 1, 1, 2);
      SymbolBottomLeft1.setRotationPoint(-2F, 6F, -1F);
      SymbolBottomLeft1.setTextureSize(128, 64);
      SymbolBottomLeft1.mirror = true;
      setRotation(SymbolBottomLeft1, 0F, 0F, 0F);
      SymbolBottomLeft2 = new ModelRenderer(this, 64, 0);
      SymbolBottomLeft2.addBox(0F, 0F, 0F, 1, 1, 2);
      SymbolBottomLeft2.setRotationPoint(-3F, 7F, -1F);
      SymbolBottomLeft2.setTextureSize(128, 64);
      SymbolBottomLeft2.mirror = true;
      setRotation(SymbolBottomLeft2, 0F, 0F, 0F);
      SymbolBottomLeft3 = new ModelRenderer(this, 64, 0);
      SymbolBottomLeft3.addBox(0F, 0F, 0F, 1, 1, 2);
      SymbolBottomLeft3.setRotationPoint(-4F, 8F, -1F);
      SymbolBottomLeft3.setTextureSize(128, 64);
      SymbolBottomLeft3.mirror = true;
      setRotation(SymbolBottomLeft3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    Foot1.render(f5);
    Foot2.render(f5);
    Foot3.render(f5);
    Foot4.render(f5);
    Pillar1.render(f5);
    Pillar2.render(f5);
    Crossbar.render(f5);
    Platform.render(f5);
    Support1.render(f5);
    Support2.render(f5);
    Support3.render(f5);
    Support4.render(f5);
    Surface.render(f5);
    Spacer1.render(f5);
    Spacer2.render(f5);
    Top.render(f5);
    Ornament1.render(f5);
    Ornament2.render(f5);
    Ornament3.render(f5);
    Ornament4.render(f5);
    Cloth1.render(f5);
    Cloth2.render(f5);
    Symbol1.render(f5);
    Symbol2.render(f5);
    SymbolTopLeft1.render(f5);
    SymbolTopLeft2.render(f5);
    SymbolTopLeft3.render(f5);
    SymbolTopRight1.render(f5);
    SymbolTopRight2.render(f5);
    SymbolTopRight3.render(f5);
    SymbolBottomRight1.render(f5);
    SymbolBottomRight2.render(f5);
    SymbolBottomRight3.render(f5);
    SymbolBottomLeft1.render(f5);
    SymbolBottomLeft2.render(f5);
    SymbolBottomLeft3.render(f5);
  }
  
  public void renderModel(float f)
  {
    Base.render(f);
    Foot1.render(f);
    Foot2.render(f);
    Foot3.render(f);
    Foot4.render(f);
    Pillar1.render(f);
    Pillar2.render(f);
    Crossbar.render(f);
    Platform.render(f);
    Support1.render(f);
    Support2.render(f);
    Support3.render(f);
    Support4.render(f);
    Surface.render(f);
    Spacer1.render(f);
    Spacer2.render(f);
    Top.render(f);
    Ornament1.render(f);
    Ornament2.render(f);
    Ornament3.render(f);
    Ornament4.render(f);
    Cloth1.render(f);
    Cloth2.render(f);
    Symbol1.render(f);
    Symbol2.render(f);
    SymbolTopLeft1.render(f);
    SymbolTopLeft2.render(f);
    SymbolTopLeft3.render(f);
    SymbolTopRight1.render(f);
    SymbolTopRight2.render(f);
    SymbolTopRight3.render(f);
    SymbolBottomRight1.render(f);
    SymbolBottomRight2.render(f);
    SymbolBottomRight3.render(f);
    SymbolBottomLeft1.render(f);
    SymbolBottomLeft2.render(f);
    SymbolBottomLeft3.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
