package com.fingersome.dungeonmasterycore.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelAltarBoccob extends ModelBase
{
	
    ModelRenderer Base;
    ModelRenderer Foot1;
    ModelRenderer Foot2;
    ModelRenderer Foot3;
    ModelRenderer Foot4;
    ModelRenderer Pillar1;
    ModelRenderer Pillar2;
    ModelRenderer Crossbar;
    ModelRenderer Platform;
    ModelRenderer Support1;
    ModelRenderer Support2;
    ModelRenderer Support3;
    ModelRenderer Support4;
    ModelRenderer Surface;
    ModelRenderer Spacer1;
    ModelRenderer Spacer2;
    ModelRenderer Top;
    ModelRenderer Ornament1;
    ModelRenderer Ornament2;
    ModelRenderer Ornament3;
    ModelRenderer Ornament4;
    ModelRenderer Cloth1;
    ModelRenderer Cloth2;
    ModelRenderer Symbol1;
    ModelRenderer Symbol2;
    ModelRenderer Symbol3;
    ModelRenderer Symbol4;
    ModelRenderer Symbol5;
    ModelRenderer Symbol6;
    ModelRenderer Symbol7;
    ModelRenderer Symbol8;
    ModelRenderer Symbol9;
    ModelRenderer Symbol10;
    ModelRenderer Symbol11;
    ModelRenderer Symbol12;
    ModelRenderer Symbol13;
    ModelRenderer Symbol15;
    ModelRenderer Symbol16;
    ModelRenderer Symbol17;
    ModelRenderer SymbolTopper1;
    ModelRenderer SymbolTopper2;
    ModelRenderer SymbolTopper3;
    ModelRenderer SymbolTopper4;
    ModelRenderer SymbolCenter1;
    ModelRenderer SymbolCenter2;
    ModelRenderer SymbolCenter3;
    ModelRenderer SymbolCenter4;
    ModelRenderer SymbolCenter5;
    ModelRenderer SymbolCenter6;
  
  public ModelAltarBoccob()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(0F, 0F, 0F, 10, 1, 6);
      Base.setRotationPoint(-5F, 22F, -3F);
      Base.setTextureSize(128, 64);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Foot1 = new ModelRenderer(this, 0, 0);
      Foot1.addBox(0F, 0F, 0F, 2, 1, 1);
      Foot1.setRotationPoint(-6F, 23F, 2F);
      Foot1.setTextureSize(128, 64);
      Foot1.mirror = true;
      setRotation(Foot1, 0F, 0F, 0F);
      Foot2 = new ModelRenderer(this, 0, 0);
      Foot2.addBox(0F, 0F, 0F, 2, 1, 1);
      Foot2.setRotationPoint(4F, 23F, 2F);
      Foot2.setTextureSize(128, 64);
      Foot2.mirror = true;
      setRotation(Foot2, 0F, 0F, 0F);
      Foot3 = new ModelRenderer(this, 0, 0);
      Foot3.addBox(0F, 0F, 0F, 2, 1, 1);
      Foot3.setRotationPoint(-6F, 23F, -3F);
      Foot3.setTextureSize(128, 64);
      Foot3.mirror = true;
      setRotation(Foot3, 0F, 0F, 0F);
      Foot4 = new ModelRenderer(this, 0, 0);
      Foot4.addBox(0F, 0F, 0F, 2, 1, 1);
      Foot4.setRotationPoint(4F, 23F, -3F);
      Foot4.setTextureSize(128, 64);
      Foot4.mirror = true;
      setRotation(Foot4, 0F, 0F, 0F);
      Pillar1 = new ModelRenderer(this, 0, 0);
      Pillar1.addBox(0F, 0F, 0F, 2, 6, 2);
      Pillar1.setRotationPoint(-4F, 16F, -1F);
      Pillar1.setTextureSize(128, 64);
      Pillar1.mirror = true;
      setRotation(Pillar1, 0F, 0F, 0F);
      Pillar2 = new ModelRenderer(this, 0, 0);
      Pillar2.addBox(0F, 0F, 0F, 2, 6, 2);
      Pillar2.setRotationPoint(2F, 16F, -1F);
      Pillar2.setTextureSize(128, 64);
      Pillar2.mirror = true;
      setRotation(Pillar2, 0F, 0F, 0F);
      Crossbar = new ModelRenderer(this, 0, 0);
      Crossbar.addBox(0F, 0F, 0F, 4, 1, 1);
      Crossbar.setRotationPoint(-2F, 19F, 0F);
      Crossbar.setTextureSize(128, 64);
      Crossbar.mirror = true;
      setRotation(Crossbar, 0F, 0F, 0F);
      Platform = new ModelRenderer(this, 0, 0);
      Platform.addBox(0F, 0F, 0F, 10, 1, 6);
      Platform.setRotationPoint(-5F, 15F, -3F);
      Platform.setTextureSize(128, 64);
      Platform.mirror = true;
      setRotation(Platform, 0F, 0F, 0F);
      Support1 = new ModelRenderer(this, 0, 0);
      Support1.addBox(0F, 0F, 0F, 1, 1, 1);
      Support1.setRotationPoint(-4F, 14F, 1F);
      Support1.setTextureSize(128, 64);
      Support1.mirror = true;
      setRotation(Support1, 0F, 0F, 0F);
      Support2 = new ModelRenderer(this, 0, 0);
      Support2.addBox(0F, 0F, 0F, 1, 1, 1);
      Support2.setRotationPoint(3F, 14F, 1F);
      Support2.setTextureSize(128, 64);
      Support2.mirror = true;
      setRotation(Support2, 0F, 0F, 0F);
      Support3 = new ModelRenderer(this, 0, 0);
      Support3.addBox(0F, 0F, 0F, 1, 1, 1);
      Support3.setRotationPoint(-4F, 14F, -2F);
      Support3.setTextureSize(128, 64);
      Support3.mirror = true;
      setRotation(Support3, 0F, 0F, 0F);
      Support4 = new ModelRenderer(this, 0, 0);
      Support4.addBox(0F, 0F, 0F, 1, 1, 1);
      Support4.setRotationPoint(3F, 14F, -2F);
      Support4.setTextureSize(128, 64);
      Support4.mirror = true;
      setRotation(Support4, 0F, 0F, 0F);
      Surface = new ModelRenderer(this, 0, 0);
      Surface.addBox(0F, 0F, 0F, 12, 1, 8);
      Surface.setRotationPoint(-6F, 13F, -4F);
      Surface.setTextureSize(128, 64);
      Surface.mirror = true;
      setRotation(Surface, 0F, 0F, 0F);
      Spacer1 = new ModelRenderer(this, 0, 0);
      Spacer1.addBox(0F, 0F, 0F, 1, 1, 4);
      Spacer1.setRotationPoint(-2F, 12F, -2F);
      Spacer1.setTextureSize(128, 64);
      Spacer1.mirror = true;
      setRotation(Spacer1, 0F, 0F, 0F);
      Spacer2 = new ModelRenderer(this, 15, 4);
      Spacer2.addBox(0F, 0F, 0F, 1, 1, 4);
      Spacer2.setRotationPoint(1F, 12F, -2F);
      Spacer2.setTextureSize(128, 64);
      Spacer2.mirror = true;
      setRotation(Spacer2, 0F, 0F, 0F);
      Top = new ModelRenderer(this, 0, 0);
      Top.addBox(0F, 0F, 0F, 6, 1, 6);
      Top.setRotationPoint(-3F, 11F, -3F);
      Top.setTextureSize(128, 64);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
      Ornament1 = new ModelRenderer(this, 0, 0);
      Ornament1.addBox(0F, 0F, 0F, 1, 1, 1);
      Ornament1.setRotationPoint(-5F, 12F, 2F);
      Ornament1.setTextureSize(128, 64);
      Ornament1.mirror = true;
      setRotation(Ornament1, 0F, 0F, 0F);
      Ornament2 = new ModelRenderer(this, 0, 0);
      Ornament2.addBox(0F, 0F, 0F, 1, 1, 1);
      Ornament2.setRotationPoint(4F, 12F, 2F);
      Ornament2.setTextureSize(128, 64);
      Ornament2.mirror = true;
      setRotation(Ornament2, 0F, 0F, 0F);
      Ornament3 = new ModelRenderer(this, 0, 0);
      Ornament3.addBox(0F, 0F, 0F, 1, 1, 1);
      Ornament3.setRotationPoint(-5F, 12F, -3F);
      Ornament3.setTextureSize(128, 64);
      Ornament3.mirror = true;
      setRotation(Ornament3, 0F, 0F, 0F);
      Ornament4 = new ModelRenderer(this, 0, 0);
      Ornament4.addBox(0F, 0F, 0F, 1, 1, 1);
      Ornament4.setRotationPoint(4F, 12F, -3F);
      Ornament4.setTextureSize(128, 64);
      Ornament4.mirror = true;
      setRotation(Ornament4, 0F, 0F, 0F);
      Cloth1 = new ModelRenderer(this, 0, 12);
      Cloth1.addBox(0F, 0F, 0F, 1, 6, 6);
      Cloth1.setRotationPoint(-6F, 14F, -3F);
      Cloth1.setTextureSize(128, 64);
      Cloth1.mirror = true;
      setRotation(Cloth1, 0F, 0F, 0F);
      Cloth2 = new ModelRenderer(this, 0, 12);
      Cloth2.addBox(0F, 0F, 0F, 1, 6, 6);
      Cloth2.setRotationPoint(5F, 14F, -3F);
      Cloth2.setTextureSize(128, 64);
      Cloth2.mirror = true;
      setRotation(Cloth2, 0F, 0F, 0F);
      Symbol1 = new ModelRenderer(this, 64, 0);
      Symbol1.addBox(0F, 0F, 0F, 4, 1, 2);
      Symbol1.setRotationPoint(-2F, 10F, -1F);
      Symbol1.setTextureSize(128, 64);
      Symbol1.mirror = true;
      setRotation(Symbol1, 0F, 0F, 0F);
      Symbol2 = new ModelRenderer(this, 64, 0);
      Symbol2.addBox(0F, 0F, 0F, 1, 1, 2);
      Symbol2.setRotationPoint(-3F, 9F, -1F);
      Symbol2.setTextureSize(128, 64);
      Symbol2.mirror = true;
      setRotation(Symbol2, 0F, 0F, 0F);
      Symbol3 = new ModelRenderer(this, 64, 0);
      Symbol3.addBox(0F, 0F, 0F, 2, 1, 2);
      Symbol3.setRotationPoint(-5F, 8F, -1F);
      Symbol3.setTextureSize(128, 64);
      Symbol3.mirror = true;
      setRotation(Symbol3, 0F, 0F, 0F);
      Symbol4 = new ModelRenderer(this, 64, 0);
      Symbol4.addBox(0F, 0F, 0F, 1, 1, 2);
      Symbol4.setRotationPoint(-6F, 7F, -1F);
      Symbol4.setTextureSize(128, 64);
      Symbol4.mirror = true;
      setRotation(Symbol4, 0F, 0F, 0F);
      Symbol5 = new ModelRenderer(this, 64, 0);
      Symbol5.addBox(0F, 0F, 0F, 2, 1, 2);
      Symbol5.setRotationPoint(-8F, 6F, -1F);
      Symbol5.setTextureSize(128, 64);
      Symbol5.mirror = true;
      setRotation(Symbol5, 0F, 0F, 0F);
      Symbol6 = new ModelRenderer(this, 64, 0);
      Symbol6.addBox(0F, 0F, 0F, 1, 1, 2);
      Symbol6.setRotationPoint(-6F, 5F, -1F);
      Symbol6.setTextureSize(128, 64);
      Symbol6.mirror = true;
      setRotation(Symbol6, 0F, 0F, 0F);
      Symbol7 = new ModelRenderer(this, 64, 0);
      Symbol7.addBox(0F, 0F, 0F, 2, 1, 2);
      Symbol7.setRotationPoint(-5F, 4F, -1F);
      Symbol7.setTextureSize(128, 64);
      Symbol7.mirror = true;
      setRotation(Symbol7, 0F, 0F, 0F);
      Symbol8 = new ModelRenderer(this, 64, 0);
      Symbol8.addBox(0F, 0F, 0F, 1, 1, 2);
      Symbol8.setRotationPoint(-3F, 3F, -1F);
      Symbol8.setTextureSize(128, 64);
      Symbol8.mirror = true;
      setRotation(Symbol8, 0F, 0F, 0F);
      Symbol9 = new ModelRenderer(this, 64, 0);
      Symbol9.addBox(0F, 0F, 0F, 4, 1, 2);
      Symbol9.setRotationPoint(-2F, 2F, -1F);
      Symbol9.setTextureSize(128, 64);
      Symbol9.mirror = true;
      setRotation(Symbol9, 0F, 0F, 0F);
      Symbol10 = new ModelRenderer(this, 64, 0);
      Symbol10.addBox(0F, 0F, 0F, 1, 1, 2);
      Symbol10.setRotationPoint(2F, 3F, -1F);
      Symbol10.setTextureSize(128, 64);
      Symbol10.mirror = true;
      setRotation(Symbol10, 0F, 0F, 0F);
      Symbol11 = new ModelRenderer(this, 64, 0);
      Symbol11.addBox(0F, 0F, 0F, 2, 1, 2);
      Symbol11.setRotationPoint(3F, 4F, -1F);
      Symbol11.setTextureSize(128, 64);
      Symbol11.mirror = true;
      setRotation(Symbol11, 0F, 0F, 0F);
      Symbol12 = new ModelRenderer(this, 64, 0);
      Symbol12.addBox(0F, 0F, 0F, 1, 1, 2);
      Symbol12.setRotationPoint(5F, 5F, -1F);
      Symbol12.setTextureSize(128, 64);
      Symbol12.mirror = true;
      setRotation(Symbol12, 0F, 0F, 0F);
      Symbol13 = new ModelRenderer(this, 64, 0);
      Symbol13.addBox(0F, 0F, 0F, 2, 1, 2);
      Symbol13.setRotationPoint(6F, 6F, -1F);
      Symbol13.setTextureSize(128, 64);
      Symbol13.mirror = true;
      setRotation(Symbol13, 0F, 0F, 0F);
      Symbol15 = new ModelRenderer(this, 64, 0);
      Symbol15.addBox(0F, 0F, 0F, 1, 1, 2);
      Symbol15.setRotationPoint(5F, 7F, -1F);
      Symbol15.setTextureSize(128, 64);
      Symbol15.mirror = true;
      setRotation(Symbol15, 0F, 0F, 0F);
      Symbol16 = new ModelRenderer(this, 64, 0);
      Symbol16.addBox(0F, 0F, 0F, 2, 1, 2);
      Symbol16.setRotationPoint(3F, 8F, -1F);
      Symbol16.setTextureSize(128, 64);
      Symbol16.mirror = true;
      setRotation(Symbol16, 0F, 0F, 0F);
      Symbol17 = new ModelRenderer(this, 64, 0);
      Symbol17.addBox(0F, 0F, 0F, 1, 1, 2);
      Symbol17.setRotationPoint(2F, 9F, -1F);
      Symbol17.setTextureSize(128, 64);
      Symbol17.mirror = true;
      setRotation(Symbol17, 0F, 0F, 0F);
      SymbolTopper1 = new ModelRenderer(this, 64, 0);
      SymbolTopper1.addBox(0F, 0F, 0F, 2, 1, 2);
      SymbolTopper1.setRotationPoint(-1F, 1F, -1F);
      SymbolTopper1.setTextureSize(128, 64);
      SymbolTopper1.mirror = true;
      setRotation(SymbolTopper1, 0F, 0F, 0F);
      SymbolTopper2 = new ModelRenderer(this, 64, 0);
      SymbolTopper2.addBox(0F, 0F, 0F, 4, 1, 2);
      SymbolTopper2.setRotationPoint(-2F, 0F, -1F);
      SymbolTopper2.setTextureSize(128, 64);
      SymbolTopper2.mirror = true;
      setRotation(SymbolTopper2, 0F, 0F, 0F);
      SymbolTopper3 = new ModelRenderer(this, 64, 0);
      SymbolTopper3.addBox(0F, 0F, 0F, 1, 1, 2);
      SymbolTopper3.setRotationPoint(-3F, -1F, -1F);
      SymbolTopper3.setTextureSize(128, 64);
      SymbolTopper3.mirror = true;
      setRotation(SymbolTopper3, 0F, 0F, 0F);
      SymbolTopper4 = new ModelRenderer(this, 64, 0);
      SymbolTopper4.addBox(0F, 0F, 0F, 1, 1, 2);
      SymbolTopper4.setRotationPoint(2F, -1F, -1F);
      SymbolTopper4.setTextureSize(128, 64);
      SymbolTopper4.mirror = true;
      setRotation(SymbolTopper4, 0F, 0F, 0F);
      SymbolCenter1 = new ModelRenderer(this, 64, 0);
      SymbolCenter1.addBox(0F, 0F, 0F, 2, 1, 2);
      SymbolCenter1.setRotationPoint(-1F, 3F, -1F);
      SymbolCenter1.setTextureSize(128, 64);
      SymbolCenter1.mirror = true;
      setRotation(SymbolCenter1, 0F, 0F, 0F);
      SymbolCenter2 = new ModelRenderer(this, 64, 0);
      SymbolCenter2.addBox(0F, 0F, 0F, 4, 1, 2);
      SymbolCenter2.setRotationPoint(-2F, 4F, -1F);
      SymbolCenter2.setTextureSize(128, 64);
      SymbolCenter2.mirror = true;
      setRotation(SymbolCenter2, 0F, 0F, 0F);
      SymbolCenter3 = new ModelRenderer(this, 64, 0);
      SymbolCenter3.addBox(0F, 0F, 0F, 2, 3, 2);
      SymbolCenter3.setRotationPoint(1F, 5F, -1F);
      SymbolCenter3.setTextureSize(128, 64);
      SymbolCenter3.mirror = true;
      setRotation(SymbolCenter3, 0F, 0F, 0F);
      SymbolCenter4 = new ModelRenderer(this, 64, 0);
      SymbolCenter4.addBox(0F, 0F, 0F, 2, 1, 2);
      SymbolCenter4.setRotationPoint(-1F, 9F, -1F);
      SymbolCenter4.setTextureSize(128, 64);
      SymbolCenter4.mirror = true;
      setRotation(SymbolCenter4, 0F, 0F, 0F);
      SymbolCenter5 = new ModelRenderer(this, 64, 0);
      SymbolCenter5.addBox(0F, 0F, 0F, 4, 1, 2);
      SymbolCenter5.setRotationPoint(-2F, 8F, -1F);
      SymbolCenter5.setTextureSize(128, 64);
      SymbolCenter5.mirror = true;
      setRotation(SymbolCenter5, 0F, 0F, 0F);
      SymbolCenter6 = new ModelRenderer(this, 64, 0);
      SymbolCenter6.addBox(0F, 0F, 0F, 2, 3, 2);
      SymbolCenter6.setRotationPoint(-3F, 5F, -1F);
      SymbolCenter6.setTextureSize(128, 64);
      SymbolCenter6.mirror = true;
      setRotation(SymbolCenter6, 0F, 0F, 0F);
  }
  
  public void renderModel(float f)
  {
    Base.render(f);
    Foot1.render(f);
    Foot2.render(f);
    Foot3.render(f);
    Foot4.render(f);
    Pillar1.render(f);
    Pillar2.render(f);
    Crossbar.render(f);
    Platform.render(f);
    Support1.render(f);
    Support2.render(f);
    Support3.render(f);
    Support4.render(f);
    Surface.render(f);
    Spacer1.render(f);
    Spacer2.render(f);
    Top.render(f);
    Ornament1.render(f);
    Ornament2.render(f);
    Ornament3.render(f);
    Ornament4.render(f);
    Cloth1.render(f);
    Cloth2.render(f);
    Symbol1.render(f);
    Symbol2.render(f);
    Symbol3.render(f);
    Symbol4.render(f);
    Symbol5.render(f);
    Symbol6.render(f);
    Symbol7.render(f);
    Symbol8.render(f);
    Symbol9.render(f);
    Symbol10.render(f);
    Symbol11.render(f);
    Symbol12.render(f);
    Symbol13.render(f);
    Symbol15.render(f);
    Symbol16.render(f);
    Symbol17.render(f);
    SymbolTopper1.render(f);
    SymbolTopper2.render(f);
    SymbolTopper3.render(f);
    SymbolTopper4.render(f);
    SymbolCenter1.render(f);
    SymbolCenter2.render(f);
    SymbolCenter3.render(f);
    SymbolCenter4.render(f);
    SymbolCenter5.render(f);
    SymbolCenter6.render(f);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    Foot1.render(f5);
    Foot2.render(f5);
    Foot3.render(f5);
    Foot4.render(f5);
    Pillar1.render(f5);
    Pillar2.render(f5);
    Crossbar.render(f5);
    Platform.render(f5);
    Support1.render(f5);
    Support2.render(f5);
    Support3.render(f5);
    Support4.render(f5);
    Surface.render(f5);
    Spacer1.render(f5);
    Spacer2.render(f5);
    Top.render(f5);
    Ornament1.render(f5);
    Ornament2.render(f5);
    Ornament3.render(f5);
    Ornament4.render(f5);
    Cloth1.render(f5);
    Cloth2.render(f5);
    Symbol1.render(f5);
    Symbol2.render(f5);
    Symbol3.render(f5);
    Symbol4.render(f5);
    Symbol5.render(f5);
    Symbol6.render(f5);
    Symbol7.render(f5);
    Symbol8.render(f5);
    Symbol9.render(f5);
    Symbol10.render(f5);
    Symbol11.render(f5);
    Symbol12.render(f5);
    Symbol13.render(f5);
    Symbol15.render(f5);
    Symbol16.render(f5);
    Symbol17.render(f5);
    SymbolTopper1.render(f5);
    SymbolTopper2.render(f5);
    SymbolTopper3.render(f5);
    SymbolTopper4.render(f5);
    SymbolCenter1.render(f5);
    SymbolCenter2.render(f5);
    SymbolCenter3.render(f5);
    SymbolCenter4.render(f5);
    SymbolCenter5.render(f5);
    SymbolCenter6.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
